# Generated by Django 5.1.3 on 2024-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='id_mascota_propio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
