# Generated by Django 5.1.3 on 2024-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_delete_tipomascota_mascota_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
