# Generated by Django 5.1.3 on 2024-12-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_id_mascota_propio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id_mascota_propio',
        ),
    ]
