# Generated by Django 5.1.1 on 2024-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_mascota_id_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='mascotas/'),
        ),
    ]
