# Generated by Django 5.1.3 on 2024-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_alter_mascota_foto'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuarios_inscritos',
            field=models.ManyToManyField(blank=True, related_name='eventos_inscritos', to='usuarios.userprofile'),
        ),
    ]
