# Generated by Django 5.1.1 on 2024-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mascotas", "0009_evento_usuarios_inscritos"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="foto_valida",
            field=models.BooleanField(default=False),
        ),
    ]
