# Generated by Django 5.1.1 on 2024-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True, max_length=100, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfiles/"),
                ),
            ],
        ),
    ]
