# Generated by Django 5.1.1 on 2024-11-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_userprofile_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='foto_persona',
            new_name='foto_mascota',
        ),
    ]
