# Generated by Django 5.1.3 on 2024-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_remove_mascota_edad_remove_mascota_tipo_mascota_and_more'),
        ('usuarios', '0004_rename_foto_persona_userprofile_foto_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_nacimiento_mascota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='foto_mascota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mascotas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_perfiles', to='mascotas.mascota'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='numero_estrellas',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
