# Generated by Django 5.1.1 on 2024-11-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mascotas", "0002_initial"),
        ("usuarios", "0003_alter_userprofile_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        help_text="Lugar aproximado donde se perdio la mascota."
                    ),
                ),
                (
                    "date_lost",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Hora aproximada en que se perdio la mascota.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detalles adicionales", null=True
                    ),
                ),
                ("is_found", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_reports",
                        to="mascotas.mascota",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_pet",
                        to="usuarios.userprofile",
                    ),
                ),
            ],
        ),
    ]
