# Generated by Django 5.1.3 on 2024-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(help_text='Lugar aproximado donde se perdio la mascota.')),
                ('date_lost', models.DateTimeField(help_text='Hora aproximada en que se perdio la mascota.')),
                ('description', models.TextField(blank=True, help_text='Detalles adicionales', null=True)),
                ('is_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
