# Generated by Django 5.1.1 on 2024-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostpets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='date_lost',
            field=models.DateTimeField(help_text='Hora aproximada en que se perdio la mascota.'),
        ),
    ]
