# Generated by Django 5.1.3 on 2024-11-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lostpets', '0001_initial'),
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to='mascotas.mascota'),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_pet', to='usuarios.userprofile'),
        ),
    ]
