# Generated by Django 5.1.3 on 2024-12-13 15:41

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('veterinary', 'Veterinary'), ('pet store', 'Pet Store'), ('dog park', 'Dog Park')], max_length=50)),
                ('adress', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('pet_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='petadvisor.petentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='usuarios.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pet_entity'), name='unique_review_per_user_and_entity')],
            },
        ),
    ]
