# Generated by Django 5.1.1 on 2024-12-09 08:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetAdvisor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "puntuation",
                    models.IntegerField(
                        help_text="Puntuacuion de 1 a 5 estrellas.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="usuarios.userprofile",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="usuarios.profesionaluser",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("author", "professional")},
            },
        ),
    ]
